### ISSUE TITLE
Where is the 'build' script target defined? Also why templateUrl

### ISSUE THREAD

**Issue by lambrospetrou** [toddmotto/angular-1-5-components-app#15]
I am trying to use your configuration as a base (ES2015 branch) for a new AngularJS+Webpack+Babel project but seeing the code I cannot find the *build:dist* target script. Is this somehow hiddenly implemented or did you just forgot to put it there?

Also, I see your last commit is 'Revert the template and use templateUrl'. I am using this in a current project already without problems, why did you have to go back to templateUrl and not just template?

Thanks a lot

**Comment by toddmotto** [comment]
Hey - so the app uses firebase, so all deployment was done directly to firebase :)

**Comment by toddmotto** [comment]
And oops forgot the template/templateUrl question:

`template`: used for string templates / literals

`templateUrl`: references HTML files (as per the `*.html` files in the app)

**Comment by exhtml** [comment]
Hey! Would be possible to deploy locally? I'm in the same problem that @lambrospetrou - I get an error about not finding the build:dist target script and I don't know how to implement it to get the 'dist' folder built. Thank you very much for your help Todd in advance!

**Comment by exhtml** [comment]
Hi folks! Following this awesome post: http://angular-tips.com/blog/2015/06/using-angular-1-dot-x-with-es6-and-webpack/ I found that is very simple, just add this script to package.json:
```
"scripts": {
    ...
    "build": "rimraf dist && webpack --bail --progress --profile",
  },
```
and now you can jus run from your terminal
`npm run build`
to get the 'dist' folder created with all the compiled files.
Thanks for your awesome work Todd!

**Comment by toddmotto** [comment]
Great to hear you fixed it! Happy coding! 💃
