### ISSUE TITLE
Error testing: should filter contacts.

### ISSUE THREAD

**Issue by msauza** [toddmotto/angular-1-5-components-app#16]
I just clone the repo, install dependencies, start and run test.. getting this error:

ContactController
      ✗ should filter contacts
        Error: [$injector:unpr] Unknown provider: ContactsControllerDirectivePro                                                                                                                vider <- ContactsControllerDirective
        http://errors.angularjs.org/1.6.1/$injector/unpr?p0=ContactsControllerDi                                                                                                                rectiveProvider%20%3C-%20ContactsControllerDirective
.....
TypeError: Cannot read property 'filteredContacts' of undefined
            at Object.<anonymous> (.../src/app/components/contact/contacts/contacts.spec.js:76:24)

ref [$onInit - lifecycle hooks in Angular 1.5](https://toddmotto.com/angular-1-5-lifecycle-hooks)

**Comment by toddmotto** [comment]
Might be the last merge, feel free to submit a PR for a fix :)
