### ISSUE TITLE
Refactor to ES6

### ISSUE THREAD

**Issue by mikeerickson** [toddmotto/angular-1-5-components-app#3]
Thanks a ton for this full project!

As per our conversation, I am going to refactor this codebase to ES6.   

Just making an issue here so that I have a ticket to associate my changes :-)

**Comment by mikeerickson** [comment]
Local branch (will issue associated PR when when completed)

```
 ~/Documents/Projects/angular/angular-1-5-components-app --> 003-refactor-es6
```

**Comment by toddmotto** [comment]
Hey Mike, awesome. I'll add you as a project collaborator on this so I can assign you the task. Check your emails for the invite :) thanks again!

**Comment by mikeerickson** [comment]
Will do!

**Comment by thomaspaillot** [comment]
I take a shoot at rewriting the app in es6 ([repo here](https://github.com/thomaspaillot/angular-1-5-components-app/tree/ES6)). The app is working but the tests are not working yet.

**Comment by mikeerickson** [comment]
@thomaspaillot what are the testing issues you are experiencing?

**Comment by mikeerickson** [comment]
@thomaspaillot Just downloaded your repo and see what the tests are doing ;-)  

I will have a closer look when I have some extra (non work) time

**Comment by thomaspaillot** [comment]
@mikeerickson Firebase initializeApp method seems to be the problem, there is a mock of firebase in the mocks folder that is attached to window and I didn't find a way to properly load it with es6 module.

First experienced with webpack and es6, so I'm not totally confortable with this yet.

Glad if you could take a look at it

**Comment by toddmotto** [comment]
I think you can just create/import/export that `mocks/` firebase, it was only something I hacked together to allow testing against the app. There's no AngularFire mocks available for this new version of Firebase.

**Comment by blowsie** [comment]
I think it would be great to see this, an example app which strictly follows the style guide.

**Comment by toddmotto** [comment]
This is complete! Huge thanks to @benbrownlol (lol) for the epic PR: https://github.com/toddmotto/angular-1-5-components-app/tree/ES2015
