### ISSUE TITLE
Refactor to TypeScript

### ISSUE THREAD

**Issue by Yerkon** [toddmotto/angular-1-5-components-app#4]
Hi Todd!
I try to refactor to TypeScript. I actually using Visual Studio project for that ;)

**Comment by Yerkon** [comment]
![default](https://cloud.githubusercontent.com/assets/4002847/18032570/8cb0de50-6d2a-11e6-8e31-02cbd10d0d46.JPG)

**Comment by Yerkon** [comment]
[preview](https://cloud.githubusercontent.com/assets/4002847/18032574/a15092c4-6d2a-11e6-9eb8-3cdf2877f7db.JPG)

**Comment by toddmotto** [comment]
Awesome, would love a TS version of this :)

**Comment by toddmotto** [comment]
Check out the [ES2015](https://github.com/toddmotto/angular-1-5-components-app/tree/ES2015) version - you could likely use that as a base?

**Comment by toddmotto** [comment]
Will close this off, lemme know if you wanted to still rock it out :)
