### ISSUE TITLE
Scss is not following your styleguide

### ISSUE THREAD

**Issue by francjpd** [toddmotto/angular-1-5-components-app#8]
Hello,

According to your [style-guide](https://github.com/toddmotto/angular-styleguide#scalable-file-structure) , each component should have it's own scss in their respective folder, but in this example your are not following your own styleguide. To be exact, you are not following the [scalable-file-structure](https://github.com/toddmotto/angular-styleguide#scalable-file-structure)'s best practice.

I guess you did that because you are not use Webpack, which let you import your scss files within each component , but i might be wrong, how ever, id like to know your thoughts on why you did that :)

Best regards.

Update 1: If you try to use the best practice in combination with the solution provided from this example, you will get errors if you try to use any variable, mixin ,etc

Possible solution: Import your base.scss into these files.

**Comment by toddmotto** [comment]
Yeah - you can do this with webpack, but the best setup is using ES2015 alongside it. The ES2015 version of this app just landed with component-based `*.scss` files in corresponding directories: https://github.com/toddmotto/angular-1-5-components-app/tree/ES2015
